import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a>Sarah.Hassan Portfolio</a>
        </h1>

        <p className={styles.description}>
          Get started by connecting with me on{" "}
          <h3 className={styles.title}>
            {" "}
            <a href="https://www.linkedin.com/in/sarah-hassan1/">
              LinkedIn!
            </a>{" "}
          </h3>
        </p>

        <div className={styles.grid}>
          <a href="https://github.com/sarahhassan1" className={styles.card}>
            <h2>Projects &rarr;</h2>
            <p>Explore other projects I have worked on.</p>
          </a>

          <a href="https://google.com" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn more about who I am and what I do!</p>
          </a>

          <a href="https://google.com" className={styles.card}>
            <h2>Profiles &rarr;</h2>
            <p>
              Discover and vote for which profile suits me best by clicking
              here!
            </p>
          </a>

          <a
            href="https://www.youtube.com/watch?v=DB_OXCj9-Sc"
            target="_blank"
            rel="noopener noreferrer"
            className={styles.card}
          >
            <h2>Destroy &rarr;</h2>
            <p>Instantly destroy your limiting beliefs.</p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
